/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Language } from "./Language";
import { LanguageCountArgs } from "./LanguageCountArgs";
import { LanguageFindManyArgs } from "./LanguageFindManyArgs";
import { LanguageFindUniqueArgs } from "./LanguageFindUniqueArgs";
import { CreateLanguageArgs } from "./CreateLanguageArgs";
import { UpdateLanguageArgs } from "./UpdateLanguageArgs";
import { DeleteLanguageArgs } from "./DeleteLanguageArgs";
import { Resume } from "../../resume/base/Resume";
import { LanguageService } from "../language.service";
@graphql.Resolver(() => Language)
export class LanguageResolverBase {
  constructor(protected readonly service: LanguageService) {}

  async _languagesMeta(
    @graphql.Args() args: LanguageCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Language])
  async languages(
    @graphql.Args() args: LanguageFindManyArgs
  ): Promise<Language[]> {
    return this.service.languages(args);
  }

  @graphql.Query(() => Language, { nullable: true })
  async language(
    @graphql.Args() args: LanguageFindUniqueArgs
  ): Promise<Language | null> {
    const result = await this.service.language(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Language)
  async createLanguage(
    @graphql.Args() args: CreateLanguageArgs
  ): Promise<Language> {
    return await this.service.createLanguage({
      ...args,
      data: {
        ...args.data,

        resume: args.data.resume
          ? {
              connect: args.data.resume,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Language)
  async updateLanguage(
    @graphql.Args() args: UpdateLanguageArgs
  ): Promise<Language | null> {
    try {
      return await this.service.updateLanguage({
        ...args,
        data: {
          ...args.data,

          resume: args.data.resume
            ? {
                connect: args.data.resume,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Language)
  async deleteLanguage(
    @graphql.Args() args: DeleteLanguageArgs
  ): Promise<Language | null> {
    try {
      return await this.service.deleteLanguage(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Resume, {
    nullable: true,
    name: "resume",
  })
  async getResume(@graphql.Parent() parent: Language): Promise<Resume | null> {
    const result = await this.service.getResume(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
