/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { EducationCreateNestedManyWithoutResumesInput } from "./EducationCreateNestedManyWithoutResumesInput";
import { Type } from "class-transformer";
import { ExperienceCreateNestedManyWithoutResumesInput } from "./ExperienceCreateNestedManyWithoutResumesInput";
import { LanguageCreateNestedManyWithoutResumesInput } from "./LanguageCreateNestedManyWithoutResumesInput";

@InputType()
class ResumeCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  educationList?: string | null;

  @ApiProperty({
    required: false,
    type: () => EducationCreateNestedManyWithoutResumesInput,
  })
  @ValidateNested()
  @Type(() => EducationCreateNestedManyWithoutResumesInput)
  @IsOptional()
  @Field(() => EducationCreateNestedManyWithoutResumesInput, {
    nullable: true,
  })
  educations?: EducationCreateNestedManyWithoutResumesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  emailAddress?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  experienceList?: string | null;

  @ApiProperty({
    required: false,
    type: () => ExperienceCreateNestedManyWithoutResumesInput,
  })
  @ValidateNested()
  @Type(() => ExperienceCreateNestedManyWithoutResumesInput)
  @IsOptional()
  @Field(() => ExperienceCreateNestedManyWithoutResumesInput, {
    nullable: true,
  })
  experiences?: ExperienceCreateNestedManyWithoutResumesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LanguageCreateNestedManyWithoutResumesInput,
  })
  @ValidateNested()
  @Type(() => LanguageCreateNestedManyWithoutResumesInput)
  @IsOptional()
  @Field(() => LanguageCreateNestedManyWithoutResumesInput, {
    nullable: true,
  })
  languages?: LanguageCreateNestedManyWithoutResumesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  resumeHash?: string | null;
}

export { ResumeCreateInput as ResumeCreateInput };
